### ISSUE TITLE
paypal issue

### ISSUE THREAD

**Issue by jasser-yah** [lpwebit/PaymentBundle#1]
An exception occurred while executing 'INSERT INTO pay_pal_request (unique_id, cmd, upload, business, bn, charset, no_note, no_shipping, cancel_return, return, notify_url, rm, paymentaction, currency_code, lc, invoice, amount_1, item_name_1, custom_data, added) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["541534b1ba946ab73defc3002226e1b4", "_cart", "1", null, "LpWebPayment_Bundle_WPS", "utf-8", "1", "1", "http:\/\/localhost\/shop\/web\/app_dev.php\/?uniqueId=541534b1ba946ab73defc3002226e1b4&paymentMethod=paypal_wps", "http:\/\/localhost\/shop\/web\/app_dev.php\/?uniqueId=541534b1ba946ab73defc3002226e1b4&redirectUrl=\/shop\/web\/app_dev.php\/&paymentMethod=paypal_wps", "http:\/\/localhost\/shop\/web\/app_dev.php\/?uniqueId=541534b1ba946ab73defc3002226e1b4&paymentMethod=paypal_wps", "2", "sale", "EUR", "IT", 1, "10", "Transaction Description", "a:0:{}", "2016-03-26 14:29:09"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'return, notify_url, rm, paymentaction, currency_code, lc, invoice, amount_1, ite' at line 1

**Comment by jasser-yah** [comment]
C:\wamp\www\shop>php app/console doctrine:schema:update --force


  [Doctrine\DBAL\Schema\SchemaException]
  There is no column with name 'uniqueId' on table 'p
  ay_pal_request'.

**Comment by lpwebit** [comment]
Hi thanks for opening this issue, and sorry for the late response.
To solve it correctly I need some other information.
Which version of Simfony are you using?
Are you using the 0.2.0 version of the bundle or the dev-master?
Are you upgrading the Bundle from a previous version or is a fresh install?

Thanks in advance
